{"metadata":{"usedHelpers":[],"marked":[],"modules":{"imports":[],"exports":{"exported":[],"specifiers":[]}}},"options":{"filename":"/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js","filenameRelative":"/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js","env":{},"retainLines":false,"highlightCode":true,"suppressDeprecationMessages":false,"presets":[],"plugins":[[[],{"polyfill":false}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],{"loose":true}],[[],{"loose":true}],[[],null],[[],{"loose":true}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],{"loose":true}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null]],"ignore":[],"code":true,"metadata":true,"ast":false,"comments":true,"compact":false,"minified":false,"sourceMap":true,"sourceMaps":true,"sourceMapTarget":"/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js.map","sourceFileName":"/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js","babelrc":false,"sourceType":"module","moduleIds":false,"passPerPreset":false,"basename":"uncaught"},"ignored":false,"code":"'use strict';\n\n/**\n * This file should only generate one failure per spec despite the fact that\n * Mocha is capable of detecting two distinct exceptions during test execution.\n */\n\nit('fails exactly once when a global error is thrown first', function (done) {\n  setTimeout(function () {\n    throw new Error('global error');\n\n    setTimeout(function () {\n      done(new Error('test error'));\n    }, 0);\n  }, 0);\n});\n\nit('fails exactly once when a global error is thrown second', function (done) {\n  setTimeout(function () {\n    done(new Error('test error'));\n  }, 0);\n\n  setTimeout(function () {\n    throw new Error('global error');\n  }, 0);\n});","ast":null,"map":{"version":3,"sources":["/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js"],"names":[],"mappings":"AAAA;;;;;;;AAOA,GAAG,wDAAH,EAA6D,UAAS,IAAT,EAAe;AAC1E,aAAW,YAAW;AACpB,UAAM,IAAI,KAAJ,CAAU,cAAV,CAAN;;AAEA,eAAW,YAAW;AACpB,WAAK,IAAI,KAAJ,CAAU,YAAV,CAAL;AACD,KAFD,EAEG,CAFH;AAGD,GAND,EAMG,CANH;AAOD,CARD;;AAUA,GAAG,yDAAH,EAA8D,UAAS,IAAT,EAAe;AAC3E,aAAW,YAAW;AACpB,SAAK,IAAI,KAAJ,CAAU,YAAV,CAAL;AACD,GAFD,EAEG,CAFH;;AAIA,aAAW,YAAW;AACpB,UAAM,IAAI,KAAJ,CAAU,cAAV,CAAN;AACD,GAFD,EAEG,CAFH;AAGD,CARD","file":"/packages/practicalmeteor:mocha/test/integration/fixtures/uncaught.js.map","sourcesContent":["'use strict';\n\n/**\n * This file should only generate one failure per spec despite the fact that\n * Mocha is capable of detecting two distinct exceptions during test execution.\n */\n\nit('fails exactly once when a global error is thrown first', function(done) {\n  setTimeout(function() {\n    throw new Error('global error');\n\n    setTimeout(function() {\n      done(new Error('test error'));\n    }, 0);\n  }, 0);\n});\n\nit('fails exactly once when a global error is thrown second', function(done) {\n  setTimeout(function() {\n    done(new Error('test error'));\n  }, 0);\n\n  setTimeout(function() {\n    throw new Error('global error');\n  }, 0);\n});\n"]},"hash":"db456eebaed6b0e4240cf0ad614998ffabb57928"}
